### ISSUE TITLE
Desync Audio v1.92

### ISSUE THREAD

**Issue by ghost** [f0e/blur#111]
**Description:**
I am experiencing audio desynchronization when using f0e/blur (version 1.92) with the following configuration. The audio is delayed by a few seconds and does not synced properly with the video output.

**Configuration:**
```yaml
[blur v1.9]
# Blur settings
blur: true
blur amount: 0.4
blur output fps: 60
blur weighting: equal

# Interpolation settings
interpolate: true
interpolated fps: 600

# Rendering settings
quality: 15
deduplicate: true
preview: true
detailed filenames: false

# Timescale settings
input timescale: 1
output timescale: 1
adjust timescaled audio pitch: false

# Filters settings
brightness: 1
saturation: 1
contrast: 1

# Advanced Rendering settings
gpu interpolation: true
gpu rendering: false
gpu type (nvidia/amd/intel): nvidia
video container: mp4
custom ffmpeg filters: 

# Advanced Blur settings
blur weighting gaussian std dev: 2
blur weighting triangle reverse: false
blur weighting bound: [0,2]

# Advanced Interpolation settings
interpolation preset: weak
interpolation algorithm: 13
interpolation block size: 8
interpolation speed: medium
interpolation mask area: 0
```

**Attachments:**
https://github.com/user-attachments/assets/5c21be5c-1476-471e-8f52-7e660315d563
